python run_train_bart_coref.py \
        --add_special_tokens=../data_object_special/simmc_special_tokens.json \
        --item2id=./item2id.json \
        --train_input_file=../data_object_special/simmc2_dials_dstc10_train_predict.txt \
        --train_target_file=../data_object_special/simmc2_dials_dstc10_train_target.txt  \
        --eval_input_file=../data_object_special/simmc2_dials_dstc10_devtest_predict.txt \
        --eval_target_file=../data_object_special/simmc2_dials_dstc10_devtest_target.txt \
        --output_dir=../coref_models/model_only_coref \
        --train_batch_size=8 \
        --output_eval_file=../coref_models/model_only_coref/report.txt \
        --num_train_epochs=8  \
        --eval_steps=3000  \
        --warmup_steps=8000